### ISSUE TITLE
Container pauses on error

### ISSUE THREAD

**Issue by seronly** [ritual-net/infernet-deploy#6]
When an error occurs in a container with a node
` [error ] Task exited: {'code': -32000, 'message': 'One of the blocks specified in filter (fromBlock, toBlock or blockHash) cannot be found.'} [__main__].`
The container throws an error only to the log, which causes it to go into pending and nothing happens. It would be correct to either terminate the process completely (so that the docker restarts the container itself) or just ignore the error =)

**Comment by stelios-ritual** [comment]
hi @seronly, what do you mean by
> causes it to go into pending and nothing happens
? What do you observe after this error, do the chain listener or processor stop processing requests? What logs do you see after? This error need not  be fatal and sounds like something the node could recover from. Hard to tell without a stack trace and more log details though.

Since this is not directly related to this repo, but to [Infernet Node](https://github.com/ritual-net/infernet-node), I am closing this but feel free to open the issue there.
